/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#include "HectorSlam_proxy.h"

/*aaaaaa*/SwigObj * _wrap_Eigen_Vector2f(float carg1, float carg2);
float _wrap_Eigen_Vector2f_x(SwigObj * carg1);
float _wrap_Eigen_Vector2f_y(SwigObj * carg1);
float _wrap_Eigen_Vector3f_x(SwigObj * carg1);
float _wrap_Eigen_Vector3f_y(SwigObj * carg1);
float _wrap_Eigen_Vector3f_z(SwigObj * carg1);
const char * _wrap_SimdInstructionSetsInUse();
void _wrap_LogOddsCell_set(SwigObj * carg1, float carg2);
float _wrap_LogOddsCell_getValue(SwigObj * carg1);
bool _wrap_LogOddsCell_isOccupied(SwigObj * carg1);
bool _wrap_LogOddsCell_isFree(SwigObj * carg1);
void _wrap_LogOddsCell_resetGridCell(SwigObj * carg1);
void _wrap_LogOddsCell_logOddsVal_set(SwigObj * carg1, float carg2);
float _wrap_LogOddsCell_logOddsVal_get(SwigObj * carg1);
void _wrap_LogOddsCell_updateIndex_set(SwigObj * carg1, int carg2);
int _wrap_LogOddsCell_updateIndex_get(SwigObj * carg1);
LogOddsCell * _wrap_new_LogOddsCell();
void _wrap_delete_LogOddsCell(LogOddsCell * carg1);
GridMapLogOddsFunctions * _wrap_new_GridMapLogOddsFunctions();
void _wrap_GridMapLogOddsFunctions_updateSetOccupied(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapLogOddsFunctions_updateSetFree(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapLogOddsFunctions_updateUnsetFree(SwigObj * carg1, SwigObj * carg2);
float _wrap_GridMapLogOddsFunctions_getGridProbability(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapLogOddsFunctions_setUpdateFreeFactor(SwigObj * carg1, float carg2);
void _wrap_GridMapLogOddsFunctions_setUpdateOccupiedFactor(SwigObj * carg1, float carg2);
void _wrap_delete_GridMapLogOddsFunctions(GridMapLogOddsFunctions * carg1);
HectorSlamProcessor * _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface_pHectorDebugInfoInterface(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5, SwigObj * carg6, SwigObj * carg7);
HectorSlamProcessor * _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5, SwigObj * carg6);
HectorSlamProcessor * _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5);
void _wrap_delete_HectorSlamProcessor(HectorSlamProcessor * carg1);
void _wrap_HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f_b(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, bool carg4);
void _wrap_HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3);
void _wrap_HectorSlamProcessor_reset(SwigObj * carg1);
SwigObj * _wrap_HectorSlamProcessor_getLastScanMatchPose(SwigObj * carg1);
SwigObj * _wrap_HectorSlamProcessor_getLastScanMatchCovariance(SwigObj * carg1);
float _wrap_HectorSlamProcessor_getScaleToMap(SwigObj * carg1);
int _wrap_HectorSlamProcessor_getMapLevels(SwigObj * carg1);
SwigObj * _wrap_HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor_i(SwigObj * carg1, int carg2);
SwigObj * _wrap_HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor(SwigObj * carg1);
void _wrap_HectorSlamProcessor_addMapMutex(SwigObj * carg1, int carg2, SwigObj * carg3);
/*aaaaaa*/SwigObj * _wrap_HectorSlamProcessor_getMapMutex(SwigObj * carg1, int carg2);
void _wrap_HectorSlamProcessor_setUpdateFactorFree(SwigObj * carg1, float carg2);
void _wrap_HectorSlamProcessor_setUpdateFactorOccupied(SwigObj * carg1, float carg2);
void _wrap_HectorSlamProcessor_setMapUpdateMinDistDiff(SwigObj * carg1, float carg2);
void _wrap_HectorSlamProcessor_setMapUpdateMinAngleDiff(SwigObj * carg1, float carg2);
DataPointContainer_Eigen_Vector2f * _wrap_new_DataPointContainer_Eigen_Vector2f_i(int carg1);
DataPointContainer_Eigen_Vector2f * _wrap_new_DataPointContainer_Eigen_Vector2f();
void _wrap_DataPointContainer_Eigen_Vector2f_setFrom(SwigObj * carg1, SwigObj * carg2, float carg3);
void _wrap_DataPointContainer_Eigen_Vector2f_add(SwigObj * carg1, SwigObj * carg2);
void _wrap_DataPointContainer_Eigen_Vector2f_clear(SwigObj * carg1);
int _wrap_DataPointContainer_Eigen_Vector2f_getSize(SwigObj * carg1);
SwigObj * _wrap_DataPointContainer_Eigen_Vector2f_getVecEntry(SwigObj * carg1, int carg2);
SwigObj * _wrap_DataPointContainer_Eigen_Vector2f_getOrigo(SwigObj * carg1);
void _wrap_DataPointContainer_Eigen_Vector2f_setOrigo(SwigObj * carg1, SwigObj * carg2);
void _wrap_delete_DataPointContainer_Eigen_Vector2f(DataPointContainer_Eigen_Vector2f * carg1);
GridMap * _wrap_new_GridMap(float carg1, SwigObj * carg2, SwigObj * carg3);
void _wrap_delete_GridMap(GridMap * carg1);
void _wrap_GridMap_updateSetOccupied(SwigObj * carg1, int carg2);
void _wrap_GridMap_updateSetFree(SwigObj * carg1, int carg2);
void _wrap_GridMap_updateUnsetFree(SwigObj * carg1, int carg2);
float _wrap_GridMap_getGridProbabilityMap(SwigObj * carg1, int carg2);
bool _wrap_GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(SwigObj * carg1, int carg2, int carg3);
bool _wrap_GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(SwigObj * carg1, int carg2, int carg3);
bool _wrap_GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(SwigObj * carg1, int carg2);
bool _wrap_GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(SwigObj * carg1, int carg2);
float _wrap_GridMap_getObstacleThreshold(SwigObj * carg1);
void _wrap_GridMap_setUpdateFreeFactor(SwigObj * carg1, float carg2);
void _wrap_GridMap_setUpdateOccupiedFactor(SwigObj * carg1, float carg2);
void _wrap_GridMap_updateByScan(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3);
void _wrap_GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i_unsigned_SS_int(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, unsigned int carg4);
void _wrap_GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3);
void _wrap_GridMap_bresenhamCellFree(SwigObj * carg1, unsigned int carg2);
void _wrap_GridMap_bresenhamCellOcc(SwigObj * carg1, unsigned int carg2);
void _wrap_GridMap_bresenham2D(SwigObj * carg1, unsigned int carg2, unsigned int carg3, int carg4, int carg5, int carg6, unsigned int carg7);
bool _wrap_GridMapBase_LogOddsCell_hasGridValue(SwigObj * carg1, int carg2, int carg3);
SwigObj * _wrap_GridMapBase_LogOddsCell_getMapDimensions(SwigObj * carg1);
int _wrap_GridMapBase_LogOddsCell_getSizeX(SwigObj * carg1);
int _wrap_GridMapBase_LogOddsCell_getSizeY(SwigObj * carg1);
bool _wrap_GridMapBase_LogOddsCell_pointOutOfMapBounds(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapBase_LogOddsCell_reset(GridMapBase_LogOddsCell * carg1);
void _wrap_GridMapBase_LogOddsCell_clear(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getMapDimProperties(SwigObj * carg1);
GridMapBase_LogOddsCell * _wrap_new_GridMapBase_LogOddsCell_f_rcEigen_Vector2i_rcEigen_Vector2f(float carg1, SwigObj * carg2, SwigObj * carg3);
void _wrap_delete_GridMapBase_LogOddsCell(GridMapBase_LogOddsCell * carg1);
void _wrap_GridMapBase_LogOddsCell_allocateArray(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapBase_LogOddsCell_deleteArray(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(SwigObj * carg1, int carg2, int carg3);
SwigObj * _wrap_GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(SwigObj * carg1, int carg2, int carg3);
SwigObj * _wrap_GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(SwigObj * carg1, int carg2);
SwigObj * _wrap_GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(SwigObj * carg1, int carg2);
void _wrap_GridMapBase_LogOddsCell_setMapGridSize(SwigObj * carg1, SwigObj * carg2);
GridMapBase_LogOddsCell * _wrap_copy_GridMapBase_LogOddsCell(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getWorldCoords(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_GridMapBase_LogOddsCell_getMapCoords(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_GridMapBase_LogOddsCell_getWorldCoordsPose(SwigObj * carg1, SwigObj * carg2);
SwigObj * _wrap_GridMapBase_LogOddsCell_getMapCoordsPose(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcEigen_Vector2f_rcEigen_Vector2i_f(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, float carg4);
void _wrap_GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcMapDimensionProperties(SwigObj * carg1, SwigObj * carg2);
void _wrap_GridMapBase_LogOddsCell_setMapTransformation(SwigObj * carg1, SwigObj * carg2, float carg3);
float _wrap_GridMapBase_LogOddsCell_getScaleToMap(SwigObj * carg1);
float _wrap_GridMapBase_LogOddsCell_getCellLength(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getWorldTmap(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getWorldTmap3D(SwigObj * carg1);
SwigObj * _wrap_GridMapBase_LogOddsCell_getMapTworld(SwigObj * carg1);
void _wrap_GridMapBase_LogOddsCell_setUpdated(SwigObj * carg1);
int _wrap_GridMapBase_LogOddsCell_getUpdateIndex(SwigObj * carg1);

/*aaaaaa*/SwigObj * Eigen_Vector2f(float carg1, float carg2) {
  return _wrap_Eigen_Vector2f(carg1, carg2);
}
float Eigen_Vector2f_x(SwigObj * carg1) {
  return _wrap_Eigen_Vector2f_x(carg1);
}
float Eigen_Vector2f_y(SwigObj * carg1) {
  return _wrap_Eigen_Vector2f_y(carg1);
}
float Eigen_Vector3f_x(SwigObj * carg1) {
  return _wrap_Eigen_Vector3f_x(carg1);
}
float Eigen_Vector3f_y(SwigObj * carg1) {
  return _wrap_Eigen_Vector3f_y(carg1);
}
float Eigen_Vector3f_z(SwigObj * carg1) {
  return _wrap_Eigen_Vector3f_z(carg1);
}
const char * SimdInstructionSetsInUse() {
  return _wrap_SimdInstructionSetsInUse();
}
void LogOddsCell_set(SwigObj * carg1, float carg2) {
  return _wrap_LogOddsCell_set(carg1, carg2);
}
float LogOddsCell_getValue(SwigObj * carg1) {
  return _wrap_LogOddsCell_getValue(carg1);
}
bool LogOddsCell_isOccupied(SwigObj * carg1) {
  return _wrap_LogOddsCell_isOccupied(carg1);
}
bool LogOddsCell_isFree(SwigObj * carg1) {
  return _wrap_LogOddsCell_isFree(carg1);
}
void LogOddsCell_resetGridCell(SwigObj * carg1) {
  return _wrap_LogOddsCell_resetGridCell(carg1);
}
void LogOddsCell_logOddsVal_set(SwigObj * carg1, float carg2) {
  return _wrap_LogOddsCell_logOddsVal_set(carg1, carg2);
}
float LogOddsCell_logOddsVal_get(SwigObj * carg1) {
  return _wrap_LogOddsCell_logOddsVal_get(carg1);
}
void LogOddsCell_updateIndex_set(SwigObj * carg1, int carg2) {
  return _wrap_LogOddsCell_updateIndex_set(carg1, carg2);
}
int LogOddsCell_updateIndex_get(SwigObj * carg1) {
  return _wrap_LogOddsCell_updateIndex_get(carg1);
}
LogOddsCell * new_LogOddsCell() {
  return _wrap_new_LogOddsCell();
}
void delete_LogOddsCell(LogOddsCell * carg1) {
  return _wrap_delete_LogOddsCell(carg1);
}
GridMapLogOddsFunctions * new_GridMapLogOddsFunctions() {
  return _wrap_new_GridMapLogOddsFunctions();
}
void GridMapLogOddsFunctions_updateSetOccupied(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapLogOddsFunctions_updateSetOccupied(carg1, carg2);
}
void GridMapLogOddsFunctions_updateSetFree(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapLogOddsFunctions_updateSetFree(carg1, carg2);
}
void GridMapLogOddsFunctions_updateUnsetFree(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapLogOddsFunctions_updateUnsetFree(carg1, carg2);
}
float GridMapLogOddsFunctions_getGridProbability(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapLogOddsFunctions_getGridProbability(carg1, carg2);
}
void GridMapLogOddsFunctions_setUpdateFreeFactor(SwigObj * carg1, float carg2) {
  return _wrap_GridMapLogOddsFunctions_setUpdateFreeFactor(carg1, carg2);
}
void GridMapLogOddsFunctions_setUpdateOccupiedFactor(SwigObj * carg1, float carg2) {
  return _wrap_GridMapLogOddsFunctions_setUpdateOccupiedFactor(carg1, carg2);
}
void delete_GridMapLogOddsFunctions(GridMapLogOddsFunctions * carg1) {
  return _wrap_delete_GridMapLogOddsFunctions(carg1);
}
HectorSlamProcessor * new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface_pHectorDebugInfoInterface(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5, SwigObj * carg6, SwigObj * carg7) {
  return _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface_pHectorDebugInfoInterface(carg1, carg2, carg3, carg4, carg5, carg6, carg7);
}
HectorSlamProcessor * new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5, SwigObj * carg6) {
  return _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i_pDrawInterface(carg1, carg2, carg3, carg4, carg5, carg6);
}
HectorSlamProcessor * new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i(float carg1, int carg2, int carg3, SwigObj * carg4, int carg5) {
  return _wrap_new_HectorSlamProcessor_f_i_i_rcEigen_Vector2f_i(carg1, carg2, carg3, carg4, carg5);
}
void delete_HectorSlamProcessor(HectorSlamProcessor * carg1) {
  return _wrap_delete_HectorSlamProcessor(carg1);
}
void HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f_b(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, bool carg4) {
  return _wrap_HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f_b(carg1, carg2, carg3, carg4);
}
void HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3) {
  return _wrap_HectorSlamProcessor_update_phectorslam_HectorSlamProcessor_rchectorslam_DataPointContainer_Sl_Eigen_Vector2f_Sg__rcEigen_Vector3f(carg1, carg2, carg3);
}
void HectorSlamProcessor_reset(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_reset(carg1);
}
SwigObj * HectorSlamProcessor_getLastScanMatchPose(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_getLastScanMatchPose(carg1);
}
SwigObj * HectorSlamProcessor_getLastScanMatchCovariance(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_getLastScanMatchCovariance(carg1);
}
float HectorSlamProcessor_getScaleToMap(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_getScaleToMap(carg1);
}
int HectorSlamProcessor_getMapLevels(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_getMapLevels(carg1);
}
SwigObj * HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor_i(SwigObj * carg1, int carg2) {
  return _wrap_HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor_i(carg1, carg2);
}
SwigObj * HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor(SwigObj * carg1) {
  return _wrap_HectorSlamProcessor_getGridMap_pchectorslam_HectorSlamProcessor(carg1);
}
void HectorSlamProcessor_addMapMutex(SwigObj * carg1, int carg2, SwigObj * carg3) {
  return _wrap_HectorSlamProcessor_addMapMutex(carg1, carg2, carg3);
}
/*aaaaaa*/SwigObj * HectorSlamProcessor_getMapMutex(SwigObj * carg1, int carg2) {
  return _wrap_HectorSlamProcessor_getMapMutex(carg1, carg2);
}
void HectorSlamProcessor_setUpdateFactorFree(SwigObj * carg1, float carg2) {
  return _wrap_HectorSlamProcessor_setUpdateFactorFree(carg1, carg2);
}
void HectorSlamProcessor_setUpdateFactorOccupied(SwigObj * carg1, float carg2) {
  return _wrap_HectorSlamProcessor_setUpdateFactorOccupied(carg1, carg2);
}
void HectorSlamProcessor_setMapUpdateMinDistDiff(SwigObj * carg1, float carg2) {
  return _wrap_HectorSlamProcessor_setMapUpdateMinDistDiff(carg1, carg2);
}
void HectorSlamProcessor_setMapUpdateMinAngleDiff(SwigObj * carg1, float carg2) {
  return _wrap_HectorSlamProcessor_setMapUpdateMinAngleDiff(carg1, carg2);
}
DataPointContainer_Eigen_Vector2f * new_DataPointContainer_Eigen_Vector2f_i(int carg1) {
  return _wrap_new_DataPointContainer_Eigen_Vector2f_i(carg1);
}
DataPointContainer_Eigen_Vector2f * new_DataPointContainer_Eigen_Vector2f() {
  return _wrap_new_DataPointContainer_Eigen_Vector2f();
}
void DataPointContainer_Eigen_Vector2f_setFrom(SwigObj * carg1, SwigObj * carg2, float carg3) {
  return _wrap_DataPointContainer_Eigen_Vector2f_setFrom(carg1, carg2, carg3);
}
void DataPointContainer_Eigen_Vector2f_add(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_DataPointContainer_Eigen_Vector2f_add(carg1, carg2);
}
void DataPointContainer_Eigen_Vector2f_clear(SwigObj * carg1) {
  return _wrap_DataPointContainer_Eigen_Vector2f_clear(carg1);
}
int DataPointContainer_Eigen_Vector2f_getSize(SwigObj * carg1) {
  return _wrap_DataPointContainer_Eigen_Vector2f_getSize(carg1);
}
SwigObj * DataPointContainer_Eigen_Vector2f_getVecEntry(SwigObj * carg1, int carg2) {
  return _wrap_DataPointContainer_Eigen_Vector2f_getVecEntry(carg1, carg2);
}
SwigObj * DataPointContainer_Eigen_Vector2f_getOrigo(SwigObj * carg1) {
  return _wrap_DataPointContainer_Eigen_Vector2f_getOrigo(carg1);
}
void DataPointContainer_Eigen_Vector2f_setOrigo(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_DataPointContainer_Eigen_Vector2f_setOrigo(carg1, carg2);
}
void delete_DataPointContainer_Eigen_Vector2f(DataPointContainer_Eigen_Vector2f * carg1) {
  return _wrap_delete_DataPointContainer_Eigen_Vector2f(carg1);
}
GridMap * new_GridMap(float carg1, SwigObj * carg2, SwigObj * carg3) {
  return _wrap_new_GridMap(carg1, carg2, carg3);
}
void delete_GridMap(GridMap * carg1) {
  return _wrap_delete_GridMap(carg1);
}
void GridMap_updateSetOccupied(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_updateSetOccupied(carg1, carg2);
}
void GridMap_updateSetFree(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_updateSetFree(carg1, carg2);
}
void GridMap_updateUnsetFree(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_updateUnsetFree(carg1, carg2);
}
float GridMap_getGridProbabilityMap(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_getGridProbabilityMap(carg1, carg2);
}
bool GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(carg1, carg2, carg3);
}
bool GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i_i(carg1, carg2, carg3);
}
bool GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_isOccupied_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(carg1, carg2);
}
bool GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(SwigObj * carg1, int carg2) {
  return _wrap_GridMap_isFree_pchectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__i(carg1, carg2);
}
float GridMap_getObstacleThreshold(SwigObj * carg1) {
  return _wrap_GridMap_getObstacleThreshold(carg1);
}
void GridMap_setUpdateFreeFactor(SwigObj * carg1, float carg2) {
  return _wrap_GridMap_setUpdateFreeFactor(carg1, carg2);
}
void GridMap_setUpdateOccupiedFactor(SwigObj * carg1, float carg2) {
  return _wrap_GridMap_setUpdateOccupiedFactor(carg1, carg2);
}
void GridMap_updateByScan(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3) {
  return _wrap_GridMap_updateByScan(carg1, carg2, carg3);
}
void GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i_unsigned_SS_int(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, unsigned int carg4) {
  return _wrap_GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i_unsigned_SS_int(carg1, carg2, carg3, carg4);
}
void GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3) {
  return _wrap_GridMap_updateLineBresenhami_phectorslam_OccGridMapBase_Sl_LogOddsCell_Sc_GridMapLogOddsFunctions_Sg__rcEigen_Vector2i_rcEigen_Vector2i(carg1, carg2, carg3);
}
void GridMap_bresenhamCellFree(SwigObj * carg1, unsigned int carg2) {
  return _wrap_GridMap_bresenhamCellFree(carg1, carg2);
}
void GridMap_bresenhamCellOcc(SwigObj * carg1, unsigned int carg2) {
  return _wrap_GridMap_bresenhamCellOcc(carg1, carg2);
}
void GridMap_bresenham2D(SwigObj * carg1, unsigned int carg2, unsigned int carg3, int carg4, int carg5, int carg6, unsigned int carg7) {
  return _wrap_GridMap_bresenham2D(carg1, carg2, carg3, carg4, carg5, carg6, carg7);
}
bool GridMapBase_LogOddsCell_hasGridValue(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_GridMapBase_LogOddsCell_hasGridValue(carg1, carg2, carg3);
}
SwigObj * GridMapBase_LogOddsCell_getMapDimensions(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getMapDimensions(carg1);
}
int GridMapBase_LogOddsCell_getSizeX(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getSizeX(carg1);
}
int GridMapBase_LogOddsCell_getSizeY(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getSizeY(carg1);
}
bool GridMapBase_LogOddsCell_pointOutOfMapBounds(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_pointOutOfMapBounds(carg1, carg2);
}
void GridMapBase_LogOddsCell_reset(GridMapBase_LogOddsCell * carg1) {
  return _wrap_GridMapBase_LogOddsCell_reset(carg1);
}
void GridMapBase_LogOddsCell_clear(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_clear(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getMapDimProperties(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getMapDimProperties(carg1);
}
GridMapBase_LogOddsCell * new_GridMapBase_LogOddsCell_f_rcEigen_Vector2i_rcEigen_Vector2f(float carg1, SwigObj * carg2, SwigObj * carg3) {
  return _wrap_new_GridMapBase_LogOddsCell_f_rcEigen_Vector2i_rcEigen_Vector2f(carg1, carg2, carg3);
}
void delete_GridMapBase_LogOddsCell(GridMapBase_LogOddsCell * carg1) {
  return _wrap_delete_GridMapBase_LogOddsCell(carg1);
}
void GridMapBase_LogOddsCell_allocateArray(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_allocateArray(carg1, carg2);
}
void GridMapBase_LogOddsCell_deleteArray(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_deleteArray(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(carg1, carg2, carg3);
}
SwigObj * GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(SwigObj * carg1, int carg2, int carg3) {
  return _wrap_GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i_i(carg1, carg2, carg3);
}
SwigObj * GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(SwigObj * carg1, int carg2) {
  return _wrap_GridMapBase_LogOddsCell_getCell_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(carg1, carg2);
}
SwigObj * GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(SwigObj * carg1, int carg2) {
  return _wrap_GridMapBase_LogOddsCell_getCell_pchectorslam_GridMapBase_Sl_LogOddsCell_Sg__i(carg1, carg2);
}
void GridMapBase_LogOddsCell_setMapGridSize(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_setMapGridSize(carg1, carg2);
}
GridMapBase_LogOddsCell * copy_GridMapBase_LogOddsCell(SwigObj * carg1) {
  return _wrap_copy_GridMapBase_LogOddsCell(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getWorldCoords(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_getWorldCoords(carg1, carg2);
}
SwigObj * GridMapBase_LogOddsCell_getMapCoords(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_getMapCoords(carg1, carg2);
}
SwigObj * GridMapBase_LogOddsCell_getWorldCoordsPose(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_getWorldCoordsPose(carg1, carg2);
}
SwigObj * GridMapBase_LogOddsCell_getMapCoordsPose(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_getMapCoordsPose(carg1, carg2);
}
void GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcEigen_Vector2f_rcEigen_Vector2i_f(SwigObj * carg1, SwigObj * carg2, SwigObj * carg3, float carg4) {
  return _wrap_GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcEigen_Vector2f_rcEigen_Vector2i_f(carg1, carg2, carg3, carg4);
}
void GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcMapDimensionProperties(SwigObj * carg1, SwigObj * carg2) {
  return _wrap_GridMapBase_LogOddsCell_setDimensionProperties_phectorslam_GridMapBase_Sl_LogOddsCell_Sg__rcMapDimensionProperties(carg1, carg2);
}
void GridMapBase_LogOddsCell_setMapTransformation(SwigObj * carg1, SwigObj * carg2, float carg3) {
  return _wrap_GridMapBase_LogOddsCell_setMapTransformation(carg1, carg2, carg3);
}
float GridMapBase_LogOddsCell_getScaleToMap(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getScaleToMap(carg1);
}
float GridMapBase_LogOddsCell_getCellLength(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getCellLength(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getWorldTmap(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getWorldTmap(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getWorldTmap3D(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getWorldTmap3D(carg1);
}
SwigObj * GridMapBase_LogOddsCell_getMapTworld(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getMapTworld(carg1);
}
void GridMapBase_LogOddsCell_setUpdated(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_setUpdated(carg1);
}
int GridMapBase_LogOddsCell_getUpdateIndex(SwigObj * carg1) {
  return _wrap_GridMapBase_LogOddsCell_getUpdateIndex(carg1);
}

