# Returns the distance to the next obstacle from the origin of frame point.header.frame_id
# in the direction of the point
#
# All units are meters.

geometry_msgs/PointStamped point
---
float32 distance
geometry_msgs/PointStamped end_point


