"""autogenerated by genpy from hector_localize/HectorIterData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HectorIterData(genpy.Message):
  _md5sum = "ecedaa7e26b5fc817a1add44c17fec5f"
  _type = "hector_localize/HectorIterData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64[9] hessian
float64 conditionNum
float64 determinant
float64 conditionNum2d
float64 determinant2d

"""
  __slots__ = ['hessian','conditionNum','determinant','conditionNum2d','determinant2d']
  _slot_types = ['float64[9]','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hessian,conditionNum,determinant,conditionNum2d,determinant2d

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HectorIterData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.hessian is None:
        self.hessian = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      if self.conditionNum is None:
        self.conditionNum = 0.
      if self.determinant is None:
        self.determinant = 0.
      if self.conditionNum2d is None:
        self.conditionNum2d = 0.
      if self.determinant2d is None:
        self.determinant2d = 0.
    else:
      self.hessian = [0.,0.,0.,0.,0.,0.,0.,0.,0.]
      self.conditionNum = 0.
      self.determinant = 0.
      self.conditionNum2d = 0.
      self.determinant2d = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_9d.pack(*self.hessian))
      _x = self
      buff.write(_struct_4d.pack(_x.conditionNum, _x.determinant, _x.conditionNum2d, _x.determinant2d))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 72
      self.hessian = _struct_9d.unpack(str[start:end])
      _x = self
      start = end
      end += 32
      (_x.conditionNum, _x.determinant, _x.conditionNum2d, _x.determinant2d,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.hessian.tostring())
      _x = self
      buff.write(_struct_4d.pack(_x.conditionNum, _x.determinant, _x.conditionNum2d, _x.determinant2d))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 72
      self.hessian = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=9)
      _x = self
      start = end
      end += 32
      (_x.conditionNum, _x.determinant, _x.conditionNum2d, _x.determinant2d,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
_struct_9d = struct.Struct("<9d")
